"""empty message

Revision ID: 564add813acb
Revises: 
Create Date: 2024-06-09 09:36:27.822776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '564add813acb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monopoly_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_tests', sa.Integer(), nullable=True),
    sa.Column('lock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_datetime'), ['datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_datetime'))

    op.drop_table('test')
    op.drop_table('monopoly_mode')
    # ### end Alembic commands ###
