# Python image
FROM python:3.9.6-alpine

# Work directory
WORKDIR /usr/src/web-sub

# Env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
ENV PYTHONUNBUFFERED 1

# Install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir logs

# Copy project
COPY . .
